// table schema generated by introspection
import { createHash } from "crypto";
import { integer, PrimaryKey } from "drizzle-orm/gel-core";
import {
  mysqlTable,
  mysqlSchema,
  AnyMySqlColumn,
  primaryKey,
  unique,
  serial,
  varchar,
  int,
  mysqlEnum,
  timestamp,
} from "drizzle-orm/mysql-core";
import { drizzle } from "drizzle-orm/singlestore";
import { appendFileSync } from "fs";

export const users = mysqlTable("users", {
  id: serial().notNull(),
  name: varchar({ length: 255 }).notNull(),
  email: varchar({ length: 255 }).notNull(),
  password: varchar({ length: 255 }).notNull(),
  role: mysqlEnum(["user", "admin"]).default("user"),
});

export const contact = mysqlTable("contacts", {
  id: serial().notNull(),
  name: varchar({ length: 255 }).notNull(),
  phone: varchar({ length: 155 }).notNull(),
  email: varchar({ length: 255 }).notNull(),
  location: varchar({ length: 255 }).notNull(),
  message: varchar({ length: 255 }).default("Null"),
});

export const loginAttempts = mysqlTable("login_attempts", {
  id: serial().notNull(),
  sessionId: varchar({ length: 255 }).notNull(),
  email: varchar({ length: 255 }).notNull(),
  attemptedAt: timestamp().notNull(),
});

async function main() {
  const db = drizzle(process.env.DATABASE_URL!);
  const appKey = process.env.APP_KEY;
  const password = appKey + "novadesk@2025__";

  db.insert(users).values({
    name: "Novadesk",
    email: "novadesk_admin@novadesk.in",
    password: createHash("sha256").update(password).digest("hex"),
    role: "admin",
  });
}

main();
